/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mochSol from "./MOCH.sol";
export type { mochSol };
import type * as predictionMarketContractSol from "./PredictionMarketContract.sol";
export type { predictionMarketContractSol };
export type { Lock } from "./Lock";
