/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mochSol from "./MOCH.sol";
export * as predictionMarketContractSol from "./PredictionMarketContract.sol";
export { Lock__factory } from "./Lock__factory";
